cmake_minimum_required(VERSION 3.8)
project(mirte_apple_detector)

if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 17)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif()
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(vision_msgs REQUIRED)
find_package(OpenCV REQUIRED)

add_executable(apple_detector src/apple_detector_node.cpp)
target_include_directories(apple_detector PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(apple_detector
  rclcpp::rclcpp
  ${sensor_msgs_TARGETS}
  ${vision_msgs_TARGETS}
  ${OpenCV_LIBS}
)

install(TARGETS apple_detector
  DESTINATION lib/${PROJECT_NAME})

install(DIRECTORY config launch
  DESTINATION share/${PROJECT_NAME})

ament_package()
